### ISSUE TITLE
DEV: search, disable Case Sensitivity

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#1]
The category search is case sensitive, which is no search standard and confuses users. The user wants search results independent of capital or small letters.

**Comment by dev-ckln** [comment]
@tobijat @ChristineDomgoergen  @darionewmonday Can you please publish the code till now that I have pushed and share the url , so that same can be tested. Or if the code is being automatically published, please share the url.

Thanks

**Comment by tobijat** [comment]
@dev-ckln 
Here's the link: https://tools.wmflabs.org/mitmachen/ (currently showing the old version, as you haven't cloned the new repository yet).

Please log into the tool-forge account, clone the repository and check-out your branch. You are then able to test the tool under https://tools.wmflabs.org/mitmachen/

We are going to test and accept the user stories via the same URL. We are going to look at the code and do a review next week and the week after and assess code quality, test-coverage and performance.

**Comment by dev-ckln** [comment]
@tobijat 
Currently on this link :- https://tools.wmflabs.org/mitmachen/
This repo is  running :- https://github.com/ionicsolutions/mitmachen.git

And I do not have the access to the same , so I am not able to deploy the code there.
I have pushed all my code in this repo :- https://github.com/wmde/mitmachen
On Fixing_issues branch

Please let me know how to proceed.

**Comment by tobijat** [comment]
@dev-ckln
The instance is yours. You can delete everything there and clone from the repository where you've pushed your code to. You can use and configure the instance as you need.

**Comment by dev-ckln** [comment]
@tobijat  you are using Kubernetes for hosting. I don't know how to use that. can you please help me in that.

**Comment by dev-ckln** [comment]
@tobijat Now that I have updated the code, I had run `webservice restart` to restart the webservice with new code.But this runs into error.
This is what I get
Could not find a public_html folder or a .lighttpd.conf file in your tool home.Type a message

**Comment by tobijat** [comment]
@dev-ckln I've not used Kubernetes before. But you don't need to use Kubernetes to clone the repository. Just ssh to the tool, remove the directory with the old version, do a git clone of the repository with your code, check out the branch with your changes and get your code running. That's it.

**Comment by dev-ckln** [comment]
@tobijat I did all those steps.But still not working. You can login into the server and see that it has the updated code there. But the link is not displaying the code.

**Comment by tobijat** [comment]
@dev-ckln I think this is the documentation you have to look at: https://wikitech.wikimedia.org/wiki/Help:Toolforge/Web#Python_(uWSGI)
I don't have any experience with Python environments, so I can't help with that. Only thing I did right now was restarting the webservice, so at least the old code isn't executed anymore.
