### ISSUE TITLE
DESIGN: Filter suggested categories by user interest

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#11]

**Comment by darionewmonday** [comment]
![Mitmachen - user interest](https://user-images.githubusercontent.com/53903644/63926451-25157800-ca4c-11e9-9772-14a31de20876.jpg)

**Comment by ChristineDomgoergen** [comment]
Hi @darionewmonday, could you upload the first screen as well, where users can click on the topic areas that are interesting for them? Thank you!

**Comment by darionewmonday** [comment]
![Set up 2](https://user-images.githubusercontent.com/53903644/64160771-d34e6280-ce3c-11e9-8fe5-ad9e63bd06d8.jpg)
![Set up 1](https://user-images.githubusercontent.com/53903644/64160772-d34e6280-ce3c-11e9-9953-3429eddc8c4a.jpg)
