### ISSUE TITLE
DEV: The tool doesn't search within words or phrases

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#12]

**Comment by darionewmonday** [comment]
Example:
If I search
nordrhein westfalen --> is found
but if I search
westfalen ---> is not found
 
If I search
Motorsportfilm ---> is found
but if I search
sportfilm ---> is not found

**Comment by dev-ckln** [comment]
Now tool searches within words and phrases

**Comment by ChristineDomgoergen** [comment]
@dev-ckln I checked and it does not work yet. If I search for "Westfalen" I still don't get suggestions for "Nordrhein-Wesfalen". Could you check please?

**Comment by dev-ckln** [comment]
Please check now.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln yes it works, but now the suggestions are sorted by alphabet. Is it possible to sort by relevance = the exactness of the matching of search term and suggested category? So for example when I search for Film, the first suggestion should be Film.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday Do you have an update on this? Without the sorting by relevance the search is not user friendly at all. This should be solved by tomorrow.

**Comment by darionewmonday** [comment]
@ChristineDomgoergen this is not considered as a bug. We can evaluate the effort and let you know if you want.

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln Okay, but then this search feature is useless. Please do not search within words or phrases then just like it was before

**Comment by darionewmonday** [comment]
@ChristineDomgoergen actually no. The feature to search within words is really helpful, it´s the first thing I have noticed from the old tool. 
I mean, the relevance order of the results, is a different topic.

**Comment by ChristineDomgoergen** [comment]
@darionewmonday In general in other contexts this is a nice feature - in this case, because there are so many topic categories I think it is quite useless if we don't sort the search results by relevance. Try with "Film": now you don't get "Film" but alphabetically sorted suggestions for film from numbers to A (afganischer Film, albanischer Film...) -- because there are only the top 10 suggestions shown (which is a good thing). But the user can only get very specific results now, which seem quite random. I would definitely vote for not searching within words or phrases if we cannot do the sorting by relevance

**Comment by darionewmonday** [comment]
@dev-ckln what is the effort to revert the code?

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln Do you have an answer to this yet?

**Comment by darionewmonday** [comment]
The code has been reverted as per your request. 

Correct @dev-ckln ?

**Comment by dev-ckln** [comment]
@darionewmonday 
The code has not been reverted yet, will do soon.

**Comment by dev-ckln** [comment]
@darionewmonday 
The code is reverted

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln I don't see a change here, the search is still searching within words or phrases? Could you estimate the effort it would take to sort the results by relevance? Thank you.

**Comment by dev-ckln** [comment]
@ChristineDomgoergen 
I'll take a look at it again as I've already reverted the code, it should work.
To answer your question for relevance - There is no relevance measure available, so its not possible to do so.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday In this case relevance means how well the result matches the search term.

**Comment by darionewmonday** [comment]
@ChristineDomgoergen can you be more specific? What do you expect here to happen?

**Comment by ChristineDomgoergen** [comment]
@darionewmonday So one example would be: I search for Film
1st result should be Film (100% matching result and search term)
2nd result could be for example Filmwissenschaft or Filmstar or 3D-Film (less than 100% matching but still very close)
next results could be Verfilmung or Affe im Film oder Afghanischer Film (not so close to Film anymore, quite specific results)

It is like the sorting search results in any online search: first results should be the most relevant results for the user. Do you know what I mean?

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
Please review, its done as per reverted code

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Code works now reverted thank you. The other question is still open though...

**Comment by darionewmonday** [comment]
@ChristineDomgoergen yes we know what you mean but we have reverted the code to the original version. It means, when you need any change or functionality here, it´s a change request. 
Otherwise, the ticket can be closed.

**Comment by ChristineDomgoergen** [comment]
@darionewmonday yes, that is fine. Could you estimate the effort for the change request?

**Comment by darionewmonday** [comment]
@ChristineDomgoergen sure. Can you please create a different ticket and close this one?
