### ISSUE TITLE
DEV: Exclude certain categories from search results and suggestions

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#14]
The user only wants to see categories which are interesting for the user. Therefore exclude categories which are not interesting for users: 
maintenance categories
geboren [year], gestorben [year]
certain undercategories are too specific for users (tbd which ones, depends on what is possible)

Solution/Comments: 
Technically there are hidden categories which should be excluded automatically.
Implement a blacklist which can be maintained manually. Tbd where this blacklist will be (part of the code, part of the repe, onwiki so that it can be edited by TIF?)

**Comment by dev-ckln** [comment]
We can allow user to select categories and then make suggest query based on that as it shown in new design. Regarding blacklist categories, we need to store the list somewhere.

**Comment by darionewmonday** [comment]
@ChristineDomgoergen blacklist is needed

**Comment by dev-ckln** [comment]
@darionewmonday , I will implement the same once I have the blacklist.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Hi Deepak, this is the blacklist:

- all maintenance categories (see here https://de.wikipedia.org/wiki/Spezial:Kategorienbaum/Wikipedia:Wartung - please expand to see all levels of sub-categories)
- all with “geboren” followed by a year
- all with “gestorben” followed by a year

**Comment by dev-ckln** [comment]
@ChristineDomgoergen How do I get blacklist categories?
How to use this tool?
Can you share some kind of a demo for this.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Hi Deepak, can't you retrieve them from the link above or via petscan query?

**Comment by dev-ckln** [comment]
@ChristineDomgoergen Got it , I have started working on it

**Comment by dev-ckln** [comment]
Mentioned categories are excluded from search and suggestions
