### ISSUE TITLE
DEV: show amount of articles per TOPIC

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#18]

**Comment by dev-ckln** [comment]
Question : We need to show the count of only category or need to count subcategory count as well

**Comment by darionewmonday** [comment]
We show the number of articles belonging to the topic

![Screenshot 2019-08-30 at 14 30 24](https://user-images.githubusercontent.com/53903644/64020894-04741d80-cb33-11e9-9d84-43fee5c1c962.png)

**Comment by dev-ckln** [comment]
Total number of articles are shown now.
