### ISSUE TITLE
DESIGN: display full category name in suggested topic areas - 1.2

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#2]
Currently the suggested categories below the search field (green buttons) are shortened automatically. This irritates users. Find a solution to display full category names or to automatically exclude categories that are longer than a certain number of characters.

Solution/Comments: Switch limitation off. Limit length to one line max, afterwards shorten.

**Comment by darionewmonday** [comment]
![Mitmachen - reload](https://user-images.githubusercontent.com/53903644/63926219-c18b4a80-ca4b-11e9-899b-767978508f2a.jpg)
