### ISSUE TITLE
DEV: develop the front-end of the tool 

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#22]
https://www.figma.com/file/RkkY3uy7fYE9PvBr4lNKx6/Mitmachen?node-id=105%3A306

**Comment by darionewmonday** [comment]
@dev-ckln

**Comment by dev-ckln** [comment]
@darionewmonday , Please let me know once the design is approved. I will implement the same.

**Comment by dev-ckln** [comment]
Front end of the tool is developed and implemented.
