### ISSUE TITLE
DEV: "Your topics": hard-coded main categories and sub-topics 

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#27]
- We can provide a list of main topics "hand-picked" (e.g.: Movies, Travel, Art, ...)
- Then, we can provide a list of sub-topics per each category, e.g.: Movies ---> Action Film 

The user will select her preferred "main topics" and get the topics and articles belonging to these Main Topics. 

Main topics are provided from our list
subtopics as well.

**Comment by darionewmonday** [comment]
@dev-ckln can you please evaluate the effort for this solution as replacement of the initial idea using real data?

**Comment by dev-ckln** [comment]
Assuming that the hard coded main categories and sub-topics will have the articles in the database, and also please let me know is there any algorithm for sorting the searched articles if incase the search responds with a hundred of articles, if that is not the case then it is not that complex.

**Comment by darionewmonday** [comment]
it looks like this:

Level 3 - Articles: "Fast & Furious 6"   <---- this article is available in Wikipedia and in our DB
Level 2 - Topics: "Motorsportfilm" <---- this topic is in our DB, and it will be included hard-coded, together with e.g. "action film" in the Level 1
Level 1 - Main categories: "Movies" <--- this doesn't exist and can be hard-coded


is it more clear? @dev-ckln 


thanks

**Comment by dev-ckln** [comment]
@darionewmonday This is very much clear , but the only question is that do we need to have some sorting for the results shown after search , for example if we get 50 results , do we need to show these 50 results to the user in some specific order?

**Comment by dev-ckln** [comment]
Top Categories are hard coded .
