### ISSUE TITLE
Provide the links for the footer

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#28]
@ChristineDomgoergen can you please help me to list the links for the footer?
thanks!!

https://www.figma.com/proto/RkkY3uy7fYE9PvBr4lNKx6/Mitmachen?node-id=480%3A1275&viewport=-386%2C493%2C0.18455646932125092&scaling=min-zoom

**Comment by ChristineDomgoergen** [comment]
https://docs.google.com/spreadsheets/d/1iUMMoTtJwcOg1_6eN213EvtT51LaLqhYAgnudRkMNjQ/edit?ts=5da0265a#gid=1206253069
