### ISSUE TITLE
CONTENT Provide contents and links for the Help panel on bottom right of the screen

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#29]
@tobijat @ChristineDomgoergen can you please help us with contents and links for the "Need Help?" panel?

thanks

**Comment by tobijat** [comment]
@darionewmonday this is a PM question and I need to delegate it to @ChristineDomgoergen

**Comment by ChristineDomgoergen** [comment]
@NewMonday @dev-ckln I added this in the translation doc, see issue #32

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you for updating. Could you add a break between the last two sentences (which should also reduce the width of the panel a bit) and add some more white space below the last sentence? Also some links are not correct:

Du brauchst Hilfe?
Lerne, wie man Artikel bearbeitet in Online-Trainings **--> should open in new tab**
Finde Hilfe in der Wikipedia:

- Startseite für neue Autorinnen und Autoren
- Übersicht aller Hilfeseiten **--> link is missing: https://de.wikipedia.org/wiki/Hilfe:%C3%9Cbersicht**
- Stelle eine Frage zur Mitarbeit in Wikipedia **--> wrong link, correct: https://de.wikipedia.org/wiki/Wikipedia:Fragen_von_Neulingen**

Du willst längerfristig dabei bleiben? -->  no link
Melde dich beim Mentorenprogramm an. **--> wrong link, correct: https://de.wikipedia.org/wiki/Wikipedia:Mentorenprogramm**
