### ISSUE TITLE
CONTENT - Contents for the home page text

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#31]
@ChristineDomgoergen

**Comment by ChristineDomgoergen** [comment]
@NewMonday @dev-ckln 
Please correct the **German Text in the Filter Tasks Menu.** 
1. We need Ü (with dots above) in the following words (see screenshot):
UNGEPR**Ü**FTER LINK
L**Ü**CKENHAFT

2. And there is a space missing in the last one, correct it is: "NUR LISTE"

3. The tooltip text for "NUR LISTE" is not correct. At the moment it is the same as "BELEGE FEHLEN". It should be correct "Dieser Artikel besteht hauptsächlich aus Listen. Formuliere Fließtext und füge ihn ein." 

![Screenshot_2019-10-18 Mitmachen in Articles](https://user-images.githubusercontent.com/53897140/67098320-437e3100-f1bc-11e9-8819-6f0f8d10574e.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen  Done. Please check and verify.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you. The explanation text for the last two (Veraltet and Nur Liste) is still incorrect, I added the information in the translation sheet, so we can keep this issue closed and resolve in the other one.
