### ISSUE TITLE
CONTENTS - Translation to German language

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#32]
@ChristineDomgoergen 
Invitation to Figma "edit mode" sent on 10.09.2019 12:12 uhr.

**Comment by ChristineDomgoergen** [comment]
@NewMonday @dev-ckln Hi Deepak, Hi Jana, I have updated the translation doc: https://docs.google.com/spreadsheets/d/1iUMMoTtJwcOg1_6eN213EvtT51LaLqhYAgnudRkMNjQ/edit?ts=5da0265a#gid=0

Please note, that there is a need of updating also some other texts on page 3, I will get back to you about that next week

**Comment by dev-ckln** [comment]
@ChristineDomgoergen  I have updated the translations except login and sign up  as German translations for these two buttons are too big which will break the designs. Can you provide us the alternate translations for these two?

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you. Laura and Jana probably have told you, that the translations are not completely finished yet, we will notifiy you when they are completely done. Then we will also provide alternatives for the Log-In.

**Comment by ChristineDomgoergen** [comment]
@darionewmonday all texts and links are final now! Thank you

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday All texts are final now in the spreadsheet, please double check if they are trasnferred correctly. There are still some translations missing or incorrect for example in:

- in the interests pop-up (all Englisch, also Wissen should be changed to "Wissenschaft")
- the task filter menu
- the help panel (last sentence + link is not shown)
- the main page
- the footer (please also make sure that all links open in new tabs here as well)

Thank you!

**Comment by dev-ckln** [comment]
@darionewmonday 
It is done.
Please verify

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you. looks good - I found two little things to improve:

- Footer: Please remove the " " marks at the beginning and end of the text below the Wikipedia Logo
- Message indicating the selected interests: instead of "more" there should be the German "weitere" (see screenshot)

![Screenshot_2019-11-01 Mitmachen in Articles(10)](https://user-images.githubusercontent.com/53897140/68025074-36793b80-fcac-11e9-9c26-d28273ceffc3.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
It is done. Please check

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you, looks good! I just noticed two little link problems in the help panel:

"Finde Hilfe in der Wikipedia" --> should not be a link
"Du willst längerfristig dabei bleiben?" --> should not be a link

Could you quickly change this? Thank you

**Comment by dev-ckln** [comment]
@ChristineDomgoergen

**Comment by dev-ckln** [comment]
@ChristineDomgoergen 
Please check it is done

**Comment by darionewmonday** [comment]
@ChristineDomgoergen can we close this one?
