### ISSUE TITLE
Topics´name can´t be broken logically since words are connected with a "_"

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#33]
<img width="250" alt="Screenshot 2019-10-07 at 12 19 17" src="https://user-images.githubusercontent.com/53903644/66304147-d980a480-e8fc-11e9-95fd-2032b34636c3.png">

The Topics´name are coming from the DB separated by a "_" thus it´s not possible to split the words over lines logically. What do you think @tobijat  ?

**Comment by tobijat** [comment]
@darionewmonday I'm not sure I understand the problem correctly. Is that a new problem that comes with new functionality, or did that problem exist with the old tool already? How did the old tool solve it?
My naive approach would be to replace underscores with spaces before the names are served to the frontend. Is there a problem with this approach?

**Comment by darionewmonday** [comment]
We´ll try your suggestion. 

thanks @tobijat

**Comment by dev-ckln** [comment]
As discussed, underscores are replaced by space in Topic names.
