### ISSUE TITLE
Dev: deploy tool on https://tools.wmflabs.org/mitmachen

### ISSUE THREAD

**Issue by tobijat** [wmde/mitmachen#35]
Right now, the tool is deployed on https://tools.wmflabs.org/mmt which was created for testing purposes.
The final version of the tool should be deployed to https://tools.wmflabs.org/mitmachen (where the old version of the tool was living).

**Comment by tobijat** [comment]
@dev-ckln @NewMonday

**Comment by dev-ckln** [comment]
Tool is now deployed on https://tools.wmflabs.org/mitmachen
