### ISSUE TITLE
Dev: add deployment guide to README

### ISSUE THREAD

**Issue by tobijat** [wmde/mitmachen#36]
Please add a short guide to the README explaining what steps needs to be done to get the tool running on Toolforge after cloning the repository.
e.g.:
- which DB tables need to be created and how to create them?
- where do the DB name and DB password have to be adjusted/changed?
- how to set-up the included cron job?
- any additional setup scripts that need to be executed?
- anything else that needs to happen besides cloning the repository to get the tool ready?

**Comment by tobijat** [comment]
@dev-ckln @NewMonday

**Comment by dev-ckln** [comment]
readme.md file is created and shared @Dario. Cant attach it here as .md files are not supported here.
