### ISSUE TITLE
DEV: enable Log-In and Sign Up with single Log In

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#40]
Hi @dev-ckln, 
the Log-In and Sign-Up links in the top bar menu do not work yet. Can you fix this? We want to have OAuth enabled here, so that you can log in with your Wikipedia-Account (single log in). Here is some documentation on that: https://www.mediawiki.org/wiki/OAuth/For_Developers
Thank you!
@NewMonday just fyi

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday  Please provide consumer key and consumer secret  for url https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose

**Comment by NewMonday** [comment]
@tobijat könnt ihr den consumer key @dev-ckln bereitstellen? Danke

**Comment by tobijat** [comment]
@NewMonday @dev-ckln 
We would need to know which "callback url" to specify and which grants the application needs.

@ChristineDomgoergen 
IMO the request should be done by your team as you are the ones owning and running the tool and the site. We can fill out the request together, but your team should be the main contact.

**Comment by dev-ckln** [comment]
@tobijat  Here is the callback url "https://tools.wmflabs.org/mitmachen/oauth-callback"

**Comment by ChristineDomgoergen** [comment]
@tobijat @dev-ckln Hi Tobi, hi Deepak, so let's assume users can log in in the tool or the tool somehow stores, that users are logged in with their Wikipedia user account. Does one of you know, if, any WMF (or other?) database would store, which users use the tool? Could we retrieve the data somehow? And if yes, how? Thank you!

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday @tobijat So we checked with the data analyst and the tracking via log in is at the moment not feasible. So we will not implement it in this iteration. Please remove the buttons in the top menu and please let us concentrate on the tracking of the tool usage in the other issue #17
