### ISSUE TITLE
BUG: Task Filter Message

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#41]
@dev-ckln @NewMonday 
I tried to find tasks in the "veraltet" category.
--> I selected all interests in step 1
--> I filtered the results to show only tasks in the "veraltet" category
--> no articles were shown but the message "XX articles found for Mythologie" remained

--> if there are no articles in the selected task category there should instead be a message stating that no articles are found: "Keine Artikel gefunden"

**Comment by dev-ckln** [comment]
@ChristineDomgoergen Done. Please check and verify.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you. 

There is the message now, when I select the task type after I did the search. But then this is what happened:

--> I selected all interests in step 1
--> I filtered the results to show only tasks in the veraltet categegory
--> I got the message: 0 Artikel gefunden in Veraltet --> great!
--> I reloaded the results (click on Kategorien neu laden)
--> I was shown tasks from all categories again althoough the filter selection stayed on "veraltet" only

--> I expected to see reloaded results from selected category veraltet only

Can you please check? Thank you

**Comment by dev-ckln** [comment]
@darionewmonday 
It is done. Please check

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday  Hi Deepak, thank you for looking into this. Now what happens is: 

--> I selected all interests in step 1
--> I filtered the results to show only tasks in the veraltet categegory
--> I got the message: 0 Artikel gefunden in Veraltet --> great!
--> I reloaded the results (click on Kategorien neu laden)
--> I was shown no articles for "Kulturwirtschaft" (probably because there where no tasks in this topic category from the task category) but I got the message "3 Artikel gefunden in Kulturwirtschaft"

--> I expected to see a correct message "0 Artikel gefunden in Kulturwirtschaft und veraltet"

I guess we need to update the message text for this case.

**Comment by darionewmonday** [comment]
Hi, 

didn´t we say that we won´t display Categories with 0 articles to be fixed?
I assume that´s the bug. @dev-ckln

**Comment by ChristineDomgoergen** [comment]
@darionewmonday No this is about categories with articles to be fixed but not articles in all task categories (veraltet, Belege fehlen etc.)

**Comment by ChristineDomgoergen** [comment]
@dev-ckln This looks good now! Only one thing in the translation: could you exchange the "and" between categories and task types in the message with an "und" (see screenshot). Thank you!
![Screenshot_2019-11-01 Mitmachen in Articles(1)](https://user-images.githubusercontent.com/53897140/68012934-cce93500-fc8b-11e9-88cb-e4df16aaf128.png)

**Comment by dev-ckln** [comment]
@darionewmonday 
It is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you, there is only one thing left with the message and one bigger issue:

The bigger issue: in the task filter, search results are only automatically updated when I deselect a task, when I add it again, results are not updated:
--> I search via search bar 
--> I see results (Screenshot 1)
--> I filter via task type filter (deselect for example Lückenhaft) 
--> I see adjusted results and the new message (when the message is shown for the first time it does not include the search term only the task types --> this should also be fixed) (Screenshot 2)
--> I select Lückenhaft again and see the same results (Screenshot 3) --> I would expect so see all results again including those for lückenhaft
--> I refesh the search via moving the cursor in the search bar and clicking return
--> the task filter still does not show all task types but all tasks without lückenhaft (Screenshot 4) --> I would expect the latest selection (all tasks) to stay


![1](https://user-images.githubusercontent.com/53897140/68024626-ebaaf400-fcaa-11e9-9f99-ac6b98d523ad.png)
![2](https://user-images.githubusercontent.com/53897140/68024625-ebaaf400-fcaa-11e9-895d-7c0dd142f2b8.png)
![3](https://user-images.githubusercontent.com/53897140/68024624-ebaaf400-fcaa-11e9-865a-7549c665ae0a.png)
![4](https://user-images.githubusercontent.com/53897140/68024623-eb125d80-fcaa-11e9-91ef-10998e727be9.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
Please check it is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you! In the message now when I select all tasks it says "all tasks" and then lists all types of tasks --> If there are all tasks selected we would not need the tasks listed
![Screenshot_2019-11-05 Mitmachen in Articles](https://user-images.githubusercontent.com/53897140/68197656-e60b2200-ffba-11e9-8af8-5a018a948721.png)

**Comment by pankshiks** [comment]
It is done @ChristineDomgoergen

**Comment by dev-ckln** [comment]
It is done @ChristineDomgoergen @darionewmonday

**Comment by ChristineDomgoergen** [comment]
@dev-ckln I commented again in #47 and we can continue the conversation there. Closing this issue.
