### ISSUE TITLE
BUG? No Tasks in the Category "ungeprüfter Link" are shown

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#42]
@dev-ckln @NewMonday 
I tried to find tasks in the category "ungeprüfter Link" but could not find any. Some time ago, this was the most common type of task. Could you please investigate, if those types of tasks are still being selected correctly? Thank you.

Edit: This seems to be only an issue, when using the interest selection. The articles with the category "ungeprüfter Link" are shown as expected, when entering a search term in the search bar. In general it seems, when entering a term in the search bar a lot more articles are found than when I enter via selecting interests. Maybe the Petscan query needs to be checked.

**Comment by dev-ckln** [comment]
@ChristineDomgoergen Done. Please check and verify.

**Comment by dev-ckln** [comment]
@ChristineDomgoergen Couldn't find anything for this, also noticed that previous code didn't even have that category.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Yes it did. When you enter search terms in the search bar you still get tasks from that category "Ungeprüfter Link" (Try with "Gedicht" for example) but not when you start with your interests.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday I can still reproduce this bug, could you look into this? If you have to prioritize for the launch tomorrow it would be B priority (=can also be fixed later than tomorrow)

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday Any news on this?

**Comment by dev-ckln** [comment]
I still don't find any subcategory with that. Can you please give example of a subcategory and category which will have ungeprüfter Link
@ChristineDomgoergen @darionewmonday

**Comment by ChristineDomgoergen** [comment]
@dev-ckln This is no topic subcategory, it is one of the task categories. I attached a screenshot, where you can see results from a search bar search
![Screenshot_2019-11-14 Mitmachen in Articles(2)](https://user-images.githubusercontent.com/53897140/68875105-8de2c700-0702-11ea-976d-2180104707e8.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen 
Can you please give example of a subcategory and category which will have ungeprüfter Link

**Comment by darionewmonday** [comment]
@ChristineDomgoergen devs can not reproduce the bug, can you please record a screencast (using Loom maybe) and send it over?

thanks

**Comment by ChristineDomgoergen** [comment]
@darionewmonday I don't have loom. Here is what happens:
1. I search via search bar
I get results
Lots of the results fall into the task category "ungeprüfter Link" (this is the most frequent task category)

2. I select interests
I get results
I do not get any results for the task category "ungeprüfter Link"

--> I think this is highly improbable, because it is the most frequent task category

**Comment by darionewmonday** [comment]
@dev-ckln can u pls check?

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen 
I checked this in detail in the DB
There is no data related to this category in the DB.
But the old developer has set this as static text in some cases. Thats why you see this category in result in some cases.

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln Thank you for checking. I do not understand yet: why do we get (dynamic) results for this task category then when we search via search bar?

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 

Because there is static text in some cases. Not in all.. so where that text is not added, you dont see it.
Let me know if I should remove static text and display the fetched results without any static text?

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday I do not understand the issue. As I see it:

Searches via search bar: I get results from all five categories of tasks (see task filter).
Searches via select interests: I get results only for four out of five categories of tasks (no results for "ungeprüfter link")

--> the search mechanism should be the same so I do not understand, why there is a difference. And I do not understand what "static text" means in this context. Please explain.

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen 
Please check it is fixed
