### ISSUE TITLE
DEV: Search: Load more Button does not load more results, article number not correct

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#43]
@dev-ckln @NewMonday 
When I enter a search term in the search bar and get more than 10 results two things do not work as expected:
1. when I scroll down to the load more button and click the button, the article selection does not update (I tried with the terms "Gedicht" and "Roman Epik")
2. the number of found articles is displayed as 10. If there are more results this should reflect in the displayed number of articles. So the message should show the number of all found articles for the search term, not only the ones displayed on the page.
Could you check this please?

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday Hello Deepak is there any update on this? This should be fixed by tomorrow since this is a serious bug, thank you!

**Comment by dev-ckln** [comment]
@ChristineDomgoergen 
It is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you. On 2. (number of articles) it still always says only 10, even if there are in total more articles. Can you check again?

Also it would be good, if I click on the load more button if the screen could jump a bit higher to the top of the page again. could you change that? Thank you.

**Comment by darionewmonday** [comment]
@dev-ckln pls fix the bug. About the page scrolling up when clicked, it can be done if it doesn´t incur in extra time spent (#newrequest)

Thank you

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln Is there any new information on this one?

**Comment by dev-ckln** [comment]
It is done @ChristineDomgoergen @darionewmonday

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Great, thank you!
