### ISSUE TITLE
DEV: Do not change capital letters of search terms

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#44]
@dev-ckln @NewMonday 
When I enter a search term, e.g. "Film" and then select from the suggestions "Film" the term in the search bar and the term in the message about the number of found articles is automatically changed to non-capital letters "film" and "9 articles found for film" . This should not happen, it should stay in capital letters if the suggested category starts with a capital letter. Can you check please? Thank you.

**Comment by dev-ckln** [comment]
@ChristineDomgoergen Done. Please check and verify.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Thank you. It is fixed for the Search Bar --> great! The display of the term should be the same in the search bar and in the message "X Artikel gefunden für SEARCH TERM". See screenshot. Could you check again?
![Screenshot_2019-10-25 Mitmachen in Articles](https://user-images.githubusercontent.com/53897140/67559723-ce5daf00-f719-11e9-9a48-92772398f42f.png)

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Great, looks good now, thank you
