### ISSUE TITLE
BUG? No articles found in "Kunst und Kultur"

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#45]
@dev-ckln 
When I select the interest "Kunst und Kultur" no articles are found. Can you please check, I think there must be a problem with the query behind it. It should find articles from this category and ALL sub-categories: https://de.wikipedia.org/wiki/Kategorie:Kunst_und_Kultur

**Comment by dev-ckln** [comment]
Please check now.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Perfect, thank you
