### ISSUE TITLE
BUG: when selecting interests after searching via the search bar the results for the interests are not shown

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#46]
@dev-ckln When searching via the search bar and then selecting interests, the search bar results are still being shown. Can you please check? The following happened:

I entered a term in the search bar (e.g. Film).
I got the results for Film
I clicked on Your interests (--> no previously selected interests)
I clicked on Edit
I selected one interest (e.g. Geographie)
I clicked on Update
I was redirected to the results for film

I did expect to see results for Geographie.

**Comment by dev-ckln** [comment]
Please check now.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Looks good, thank you
