### ISSUE TITLE
Task filter does not filter new searches via search bar

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#47]
@dev-ckln Hi Deepak, the task filter does not filter new searches:

I selected two types of tasks in the task filter
I entered a search term in the search bar (e.g. Gedicht)
I clicked return
I got results including all types of tasks

I expected to see only results for the selected types of tasks

Could you please check?

**Comment by dev-ckln** [comment]
@darionewmonday 
It is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday Thank you, looks better now. Like in Issue 41 the message I get needs to be updated because right now it only refers to the type of task "1 Artikel gefunden in Lückenhaft" but should still refer to the search term as well "1 Artikel gefunden in Gedicht und Lückenhaft"

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen 
Please check it is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Again as in already commented #41 for the message it is
If all tasks are selected --> message should not list all tasks but only show search term / category
if less than all tasks are selected (the task filter is active) --> message should indicate search term / category and types of selected tasks

**Comment by pankshiks** [comment]
It is done @ChristineDomgoergen

**Comment by dev-ckln** [comment]
It is done @ChristineDomgoergen @darionewmonday

**Comment by ChristineDomgoergen** [comment]
@dev-ckln HI Deepak, almost good now, I just found another bug though:
I search via search bar or select interests
I get results
I change the task filter and deselect a random task --> message is fine, all good
I change the task filter again to show all tasks --> message lists search term, all tasks and is doubled (see screenshot)

can you please check? Thank you.
![Screenshot_2019-11-14 Mitmachen in Articles](https://user-images.githubusercontent.com/53897140/68874269-36902700-0701-11ea-8f90-74fe06f13189.png)
![Screenshot_2019-11-14 Mitmachen in Articles(1)](https://user-images.githubusercontent.com/53897140/68874332-5293c880-0701-11ea-8553-32abefd5fd8b.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
It is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln @darionewmonday I can still replicate it (see screenshot). The problem is the message:
![Screenshot_2019-11-18 Mitmachen in Articles](https://user-images.githubusercontent.com/53897140/69056865-1fa74880-0a11-11ea-9ea2-1a582f928926.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen 
It is fixed.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Perfect, thank you
