### ISSUE TITLE
Show category-selection / update-button above the fold (without scrolling)

### ISSUE THREAD

**Issue by ghost** [wmde/mitmachen#48]
As user
I want to see the "update"-button when selecting desired categories
In order to not asking myself "what now" after having selected them.

-> currently, for large screens/desktop-pc's, the "update" button is out of sight / below the fold

![image](https://user-images.githubusercontent.com/55130789/67493045-97cf5800-f677-11e9-84e4-a4c5e8d4d913.png)

(there seems to be a breakpoint at 1200px which introduces some space above the selection pop-up, causing the update-button to disappear)

**Comment by dev-ckln** [comment]
@LukasWMDE If you need pop-up without scroll then we need to optimise little design changes like decrease the height of boxes with updating some spaces. With new design optimisations the pop up will look like this. Please check and confirm. 
![image](https://user-images.githubusercontent.com/48859836/67579381-012b9580-f762-11e9-892b-832a9dce55b8.png)

**Comment by darionewmonday** [comment]
It looks better with squared boxes. A solution can be to move the button on
top of the squares rather than leaving it below.



Il ven 25 ott 2019, 10:30 Deepak <notifications@github.com> ha scritto:

**Comment by ghost** [comment]
I see 3 options:
* reduce space above pop-up for screens above 1200 px (@dev-ckln , could you please comment on feasability? This would keep the pop-up the way it is, just move it a little higher)
* reduce height of tiles (my 2nd choice: I actually kind of like the rectangular tiles)
* move update-button on top (my 3rd choice: would lead either to differences between mobile and desktop or reduce mobile usability, if you keep the update-button on top in mobile; also, the pop-up would still end below the fold)

@ChristineDomgoergen what is your opinion?

**Comment by darionewmonday** [comment]
Hi everyone,

I suggest to go for the low hanging fruit option (number 3) since basically
everything is feasible but listed under change request, meaning we have to
calculate a budget for the change.

Nevertheless, to move a button is not a big deal.


Thanks!

Il lun 28 ott 2019, 02:56 LukasWMDE <notifications@github.com> ha scritto:

**Comment by darionewmonday** [comment]
@dev-ckln please move the button up, top-right corner.

**Comment by dev-ckln** [comment]
@darionewmonday 
It is done.
I have updated it for tablet and larger than tablet screen sizes

**Comment by ChristineDomgoergen** [comment]
@dev-ckln great, thank you!
