### ISSUE TITLE
DEV: tooltip Information should appear faster

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#5]
Use Javascript Tooltip.

**Comment by dev-ckln** [comment]
Where do we require the tooltip?

**Comment by darionewmonday** [comment]
![Screenshot 2019-08-30 at 14 25 26](https://user-images.githubusercontent.com/53903644/64020523-13a69b80-cb32-11e9-95f4-f7592150defc.png)

**Comment by dev-ckln** [comment]
In the new design, this seems to be almost instant so we don't need to add javascript tooltip.

**Comment by darionewmonday** [comment]
How do you show the information if not in a JavaScript tooltip?

Il gio 5 set 2019, 12:34 Deepak <notifications@github.com> ha scritto:

**Comment by dev-ckln** [comment]
Every li element will have tooltip text below it, using css hover we can show. No need to add additional tooltip plugin/library.
