### ISSUE TITLE
DESIGN: Interests Pop-up to open automatically if I don´t have any interest preselected

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#50]
@dev-ckln 

If I have no interests selected already and I come to the page "my interests", the pop-up has to open automatically and prompt the selection. 

Thanks

**Comment by dev-ckln** [comment]
@darionewmonday 
It is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Now when I enter a term in the search bar and click return the pop-up opens. This is not correct. I expect to see search results. The pop-up should only open if I click on "Deine Themen" and have no interests preselected

**Comment by darionewmonday** [comment]
@dev-ckln 

WHEN
the user has not selected any interest yet
AND
clicks on the "Deine Themen" button
ONLY THEN
when the page loads, the popup with interests must open

IF
the user has already selected some interests
AND
clicks on "Deine Themen"
WHEN
the page loads
THEN
do not open the pop-up automatically
BUT
open it only when the user clicks on "edit interests"

**Comment by dev-ckln** [comment]
@darionewmonday 
Please check it is done

**Comment by darionewmonday** [comment]
@ChristineDomgoergen can we close this one?
