### ISSUE TITLE
Bug: Filter by Task autmatically set on "no selection" 

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#51]
@dev-ckln @darionewmonday 
The task filter is per default set on no tasks selected, when I change the selection of my interests.

This is what happens:
--> I select my interests and find articles as usual --> all good
--> I click on Auswahl ändern and change the selection in the Pop-Up (which is not translated yet!)
--> I find 0 articles. 

I checked and it is not because there are not articles but because in the task filter there is no type of tasks selected --> please fix: per default all types of task should be selected

Edit: this happens also when I start via search bar and then change to my interests, even if I had no interests preselected. --> seems to be ocurring always after the pop-up was shown

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
 I could find it working.. 
Please  share screenshots for detailed explanation!

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Hi Deepak, please find a screenshot attached.
![Screenshot_2019-11-01 Mitmachen in Articles(4)](https://user-images.githubusercontent.com/53897140/68023278-054a3c80-fca7-11e9-97e4-13d023510a7a.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
Can you please check again, I am not able to replicate the same

**Comment by ChristineDomgoergen** [comment]
@dev-ckln yes correct, now it seems to work. Perfect :-)

**Comment by ChristineDomgoergen** [comment]
Hi @dev-ckln @darionewmonday, now the bug seems to be there again:
always when I change the task selection and then click on "favourite topics" the task filter is set on no selection and there are 0 results shown. Can you please check again? Thank you.

**Comment by darionewmonday** [comment]
@ChristineDomgoergen this is not a bug.

The behaviour of the filter on the right is simply to filter after the results are shown.

WHEN
The results are displayed
THEN
the user can filter the results

WHEN
the user changes page
THAN
We need first to show results
AND
then the user can filter again

Same thing happens when the user searches after the filtering. 
The filters reset, then we display results, then the user can filter again. 

Like Zalando, Amazon, etc 

Correct @dev-ckln ?

**Comment by dev-ckln** [comment]
@darionewmonday 
When new results are loaded then filters are kept the same, after loading results we automatically apply the existing filters.

**Comment by ChristineDomgoergen** [comment]
Yes, that totally makes sense. But please check if you can reproduce the bug, because in this case the filter is automatically switches from ALL TASKS selected to NO TASKS selected, without the user applying any changes...

**Comment by darionewmonday** [comment]
@dev-ckln pls check

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen 
It is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln great, thank you.
