### ISSUE TITLE
Content: Translate "My Interests Pop-Up"

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#52]
@dev-ckln @darionewmonday Please quickly update translations for "My interests Pop-Up" --> the texts should be the same as on the main page (see two screenshots attached).
![Screenshot_2019-11-01 Mitmachen](https://user-images.githubusercontent.com/53897140/68010862-05861000-fc86-11e9-8bfc-3f6f767bfbb0.png)
![Screenshot_2019-11-01 Mitmachen in Articles](https://user-images.githubusercontent.com/53897140/68010863-05861000-fc86-11e9-9ad7-da66696ace2b.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen  @darionewmonday 
Please check, ii is done

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Yes perfect, thank you
