### ISSUE TITLE
Performance Issues?

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#53]
Hi @darionewmonday @dev-ckln I had some performance issues, one time 502 bad gateway, and another error (see screenshot). Not sure if it is a general problem or just punctually, can you please check?
![Screenshot_2019-11-01 Mitmachen in Articles(2)](https://user-images.githubusercontent.com/53897140/68016532-168a4d80-fc95-11e9-86c0-86572c847d26.png)

Edit: two times 502 when refreshing the page

**Comment by dev-ckln** [comment]
@darionewmonday 

The error  is showing  because of bad merge.
bad gateway is because server is starting up.
It is resolved

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Perfect, thank you.
