### ISSUE TITLE
No interest pop-up when clicked on my interests

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#54]
@darionewmonday @dev-ckln When I click on my interests afterthe tool now reloads the topics:
--> i select interests and click on update
--> i see article results
--> i click on my interests again
--> for a second the old transition page appears (with the "Interessen bearbeiten" button) and then the categories (topics) are reloaded and new results are shown

I would expect instead to open the selection pop-up.

**Comment by darionewmonday** [comment]
@ChristineDomgoergen let us check.

The popup should open only in 2 cases:
1) Automatically, when the user hasn´t picked any interest yet and I open "my interests page"
2) When I click "update interests"

**Comment by dev-ckln** [comment]
@darionewmonday 
It is working as per the requirements you shared

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln yes, this is fine, thanks for implementing. But before this change the pop-up also opened when you clicked on "my interests", respectively there was the intermediary page with the "edit interests" button, right? Now we do not have this page any more, which adds one case. So we have three cases:
1. see above
2. see above 
3. when I click "my interests"

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen 
Please confirm.
Now the popup will open in these three cases:

1. Automatically, when the user hasn´t picked any interest yet and I open "my interests page"
2. When I click "update interests"
3. when I click "my interests"

Please provide an explanation!

**Comment by darionewmonday** [comment]
@dev-ckln I have just double-tested it and the way it works right now looks 100% correct. 
can you confirm @ChristineDomgoergen ?

**Comment by ChristineDomgoergen** [comment]
@darionewmonday @dev-ckln No for me it does not work if I am on page 2 and then click my interests there is no pop-up shown but the categories are reloaded

**Comment by darionewmonday** [comment]
@ChristineDomgoergen I can see articles and categories reloading when I go back-forth to Deine Themen, but the popup should not open. It should only open when I click on "Auswahl ändern".

Or are not understanding what you wish to have?

**Comment by ChristineDomgoergen** [comment]
@darionewmonday yes I guess there is a misunderstanding. As a user I do not want the articles and categories to reload when I click on my interests. When I want to reload I will click reload categories. When I click on my interests I want to edit my interests. Therefore the pop-up should open. Do you understand what I mean?

Also I always see for a second the previous intermediary page, where you could click on the button edit interests before new articles are shown. Too fast for a screenshot, sorry. This should not happen.

**Comment by darionewmonday** [comment]
@dev-ckln 

1) Remove the automatic reload of categories 
2) Remove the split-second old screen from appearing on the loading of the page

thanks

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen
It is done. Please check

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Okay, the split second screen is not there anymore, thank you. But I don't understand @darionewmonday: now nothing happens, when I click on my interests - although it is a button? What is the idea behind this? Why does the pop-up for interest selection not open?

**Comment by darionewmonday** [comment]
@ChristineDomgoergen the pop-up opens not when I click on "Your interests" but when I come to "my interests" page and there are no results to be shown because I have not selected any interest. 

IF
User comes to Your interests page
AND
No results can be shown because no interests have been selected
THEN
open pop up
ELSE
Open pop-up only when I click on "Edit interests"

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
It is done.
Please check and close or let me know if any revisions required!
