### ISSUE TITLE
Bug: previous interest selection shown but not included in search

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#55]
--> I refresh the page or go back to the main page (e.g. via the Logo in the top menue)
--> the previously selected interests are still shown and marked green
--> I click on update
--> I get a message: no results found
--> I go back to my interests and there are no interests preselected anymore

--> I would instead expect to get results for the preselected interests

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
This is something that was deliberately made to change. We are clearing localstorage upon refresh.

**Comment by ChristineDomgoergen** [comment]
@dev-ckln yes this is also a good solution, clear localstorage. But then we also want the preselection of my interests to be cleared. Right now, when I refresh my previous selection is still shown (dark green tiles)

**Comment by dev-ckln** [comment]
@darionewmonday @ChristineDomgoergen 
It is done. Please check

**Comment by ChristineDomgoergen** [comment]
@dev-ckln Yes it now works when I go back to home via Wikipedia Logo. But now I have a bug in the interest selection and message about interests:

--> I selected Geografie and clicked on find articles
--> results for more interests than geografie were shown (see screenshot for selection provided by tool)
--> also the message indicating which interests are selected does not count correctly (sometimes it says +11 more, but there are only 8 in total)
![Screenshot_2019-11-01 Mitmachen in Articles(7)](https://user-images.githubusercontent.com/53897140/68023634-016aea00-fca8-11e9-9c21-29a4dce96fe2.png)
![Screenshot_2019-11-01 Mitmachen in Articles(6)](https://user-images.githubusercontent.com/53897140/68023635-016aea00-fca8-11e9-80e9-eb917ab509b4.png)

**Comment by dev-ckln** [comment]
@ChristineDomgoergen @darionewmonday 
It is done. Please check

**Comment by ChristineDomgoergen** [comment]
@dev-ckln great, thank you!
