### ISSUE TITLE
Integration of a page view statistics in mitmachen/stats

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#59]
**Integration of a page view statistics in mitmachen/stats similar to those in Wikipedia articles ([example here](https://tools.wmflabs.org/pageviews/?project=de.wikipedia.org&platform=all-access&agent=user&start=2020-02-03&end=2020-02-23&pages=K%C3%B6ln)).** 

Requirements:

- page views are shown for freely selectable date ranges
- page views can be retrieved on a daily basis
- page views are shown for the selected date range as sum, actual daily numbers and as daily average

**Comment by darionewmonday** [comment]
The new module must be embedded in the Stat page https://tools.wmflabs.org/mitmachen/stats

When installing the new widget, pls check the bullet points from Christine here above **and** the scheme I gave you https://prnt.sc/r06rt4

@dev-ckln

**Comment by dev-ckln** [comment]
Please check the points now, last is not possible with the current view and store.
