### ISSUE TITLE
Add a link in the footer of the tool

### ISSUE THREAD

**Issue by ChristineDomgoergen** [wmde/mitmachen#61]
Add a link to https://tools.wmflabs.org/mitmachen/stats in the footer of the tool:

link name = "Abrufstatistik"

![Unbenannte Zeichnung](https://user-images.githubusercontent.com/53897140/75162006-12d77680-571d-11ea-8682-9f02ffbc0c59.jpg)

**Comment by darionewmonday** [comment]
@dev-ckln

**Comment by dev-ckln** [comment]
Done
