### ISSUE TITLE
DESIGN: Making the "task" (article) in the tool visible

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#8]
Article preview with task instructions

**Comment by darionewmonday** [comment]
![Mitmachen - visible task](https://user-images.githubusercontent.com/53903644/63926047-76713780-ca4b-11e9-9531-c71c2d70d69e.jpg)

**Comment by darionewmonday** [comment]
Es ist noch nicht gestyled, was denkt ihr?
@ChristineDomgoergen 
@tobijat

**Comment by ChristineDomgoergen** [comment]
@darionewmonday Hi Dario,
also ich finde es grundsätzlich gut! Folgendes fällt mir noch auf:

- Der Wartungsbaustein (hier: Belege fehlen und die kleine Info unten mit dem Link) ist in der Vorschau nicht sichtbar. Wir hatten ja überlegt, dass der User hier eine standardisierte Hilfe bekommt und in dem Fenster irgendwie markiert sieht, wonach er in Wikipedia suchen muss (dem Wartungsbaustein). Kannst du das noch einbauen?
- man könnte überlegen noch einen Hilfelink zu Instructions in die linke Spalte zu integrieren? Oder denkst du es wird dann zu voll? Ich kann mir vorstellen, dass User erst im Angesicht des Tasks merken, was sie nicht wissen
- ich kann mir vorstellen, dass man das "To Do" oben auf dem grünen Hintergrund überliest. Vllt. noch klarer zeigen, dass in der Spalte wichtige Infos stehen?

**Comment by ghost** [comment]
@darionewmonday Wird es möglich sein, in dem iFrame direkt zu editieren?

**Comment by darionewmonday** [comment]
@LukasWMDE so weit dass ich verstanden habe, nein. 

Wir überlegen jetzt an einen neuen Flow:

1) Mitmachen tool --> Artikel finden
2) Click auf Artikel
3) iFrame mit Info (mandatory zwischen Step)
4) Artikel auf Wikipedia
